# ==================== 开发配置文件 ====================
spring:
  # ==================== 数据存储配置 ====================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ↓↓↓↓↓↓ 数据库连接配置（需替换） ↓↓↓↓↓↓
    url: jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
    hikari:
      connection-timeout: 30000      # 连接超时(ms)
      maximum-pool-size: 20         # 最大连接数
      minimum-idle: 5               # 最小空闲连接

  redis:
    # ↓↓↓↓↓↓ Redis配置（取消注释并替换） ↓↓↓↓↓↓
    database: 1
    host: localhost
    port: 6379
    password: # 密码为空时保持注释
    timeout: 5000ms                # 连接超时时间
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms             # -1表示无限制
        max-idle: 10
        min-idle: 0
    # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

# ==================== 文件存储服务 ====================
cos:
  client:
    # ↓↓↓↓↓↓ 腾讯云COS配置（需替换） ↓↓↓↓↓↓
    accessKey: xxx
    secretKey: xxx
    region: ap-shanghai
    bucket: example-bucket

minio:
  # ↓↓↓↓↓↓ MinIO配置（需替换） ↓↓↓↓↓↓
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: default-bucket
  secure: false                    # HTTPS连接
  region: us-east-1

# ==================== 智能服务配置 ====================
ai:
  # ↓↓↓↓↓↓ AI服务密钥（需替换） ↓↓↓↓↓↓
  apikey: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  provider: openai                # [openai|aliyun|xunfei]
  timeout: 30s                    # API调用超时

# ==================== 搜索服务配置 ====================
elasticsearch:
  # ↓↓↓↓↓↓ ES配置（取消注释并替换） ↓↓↓↓↓↓
  enabled: false
  uris: http://localhost:9200
  username: elastic
  password: changeme
  connection-timeout: 10s
  socket-timeout: 30s

# ==================== 第三方服务集成 ====================
wx:
  mp:
    # ↓↓↓↓↓↓ 微信公众号配置（需替换） ↓↓↓↓↓↓
    token: WECHAT_TOKEN
    aesKey: WECHAT_AES_KEY
    appId: wx_app_id
    secret: wx_app_secret
    config-storage:
      type: redisson
      redis:
        host: 127.0.0.1
        port: 6379
        database: 2               # 独立数据库

  open:
    # ↓↓↓↓↓↓ 微信开放平台配置（需替换） ↓↓↓↓↓↓
    appId: wx_open_appid
    appSecret: wx_open_secret

github:
  # ↓↓↓↓↓↓ GitHub OAuth配置（需替换） ↓↓↓↓↓↓
  client-id: github_client_id
  client-secret: github_client_secret
  redirect-uri: https://api.example.com/oauth/github/callback
  scope: user:email

# ==================== 安全认证配置 ====================
sa-token:
  # ↓↓↓↓↓↓ 会话令牌配置 ↓↓↓↓↓↓
  token-name: shing-sa-token
  timeout: 300                   # 使用Duration格式
  active-timeout: -1             # 永不过期
  is-concurrent: true            # 允许并发登录
  is-share: true                 # 共享Token
  token-style: tik               # Token生成风格
  token-prefix: "Bearer"         # 请求头前缀
  is-log: false                  # 生产环境关闭日志